#############################
# Builder Stage (Debian)
#############################
FROM debian:bookworm AS builder

LABEL version="develop"

# Set noninteractive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive
# Install system packages for building
RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf \
    automake \
    build-essential \
    ca-certificates \
    gfortran \
    git \
    libblas-dev \
    liblapack-dev \
    libltdl-dev \
    libnetcdf-c++4-dev \
    libnetcdf-dev \
    libreadline-dev \
    libsuitesparse-dev \
    libtool \
    pkg-config \
    wget \
    && rm -rf /var/lib/apt/lists/*

# Get sources
RUN git clone -b develop https://public.gitlab.polimi.it/DAER/mbdyn.git /opt/mbdyn
WORKDIR /opt/mbdyn
RUN ./bootstrap.sh
RUN <<'EOF'
./configure
make -j$(nproc)
make install
make test
make clean
EOF

#############################
# Final Stage (Debian)
#############################
FROM debian:bookworm AS final

LABEL version="develop"

# Copy the MBDyn binaries and libraries from the builder stage
COPY --from=builder /usr/local/mbdyn /usr/local/mbdyn

# Set noninteractive mode for apt-get
ENV DEBIAN_FRONTEND=noninteractive
# Install packages for runtime requirements
RUN apt-get update && apt-get install -y --no-install-recommends \
    gfortran \
    libblas-dev \
    liblapack-dev \
    libltdl-dev \
    libnetcdf-c++4-dev \
    libnetcdf-dev \
    libreadline-dev \
    libsuitesparse-dev \
    && rm -rf /var/lib/apt/lists/*

# Setup mbdynuser
RUN <<'EOF'
# Create a nonroot user
useradd -ms /bin/bash mbdynuser
# Change ownership of the MBDyn directory to the nonroot user
chown -R mbdynuser:mbdynuser /usr/local/mbdyn
# Create a home folder for the user with correct permissions for outputs
mkdir -p /home/mbdynuser
chown -R mbdynuser:mbdynuser /home/mbdynuser
EOF

# Adjust PATH so that the mbdyn binary is available
ENV PATH="/usr/local/mbdyn/bin:${PATH}"

# Switch to nonroot user
USER mbdynuser
WORKDIR /home/mbdynuser

# Use mbdyn as the entrypoint (override with /bin/bash to get an interactive shell)
ENTRYPOINT ["mbdyn"]
