# This file is a template, and might need editing before it works on your project.
# This is a sample GitLab CI/CD configuration file that should run without any modifications.
# It demonstrates a basic 3 stage CI/CD pipeline. Instead of real tests or scripts,
# it uses echo commands to simulate the pipeline execution.
#
# A pipeline is composed of independent jobs that run scripts, grouped into stages.
# Stages run in sequential order, but jobs within stages run in parallel.
#
# For more information, see: https://docs.gitlab.com/ee/ci/yaml/index.html#stages
#
# You can copy and paste this template into a new `.gitlab-ci.yml` file.
# You should not add this template to an existing `.gitlab-ci.yml` file by using the `include:` keyword.
#
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Getting-Started.gitlab-ci.yml

variables:
  MBD_INSTALL_PREFIX: "/home/gitlab-runner/local/mbdyn-test-install/" ## Local installation directory
  MBD_BUILD_DIR: "/home/gitlab-runner/install/mbdyn-test-build/" ## Local build directory
  MBD_NUM_BUILD_JOBS: "12" # Run make -j '$MBD_NUM_BUILD_JOBS'
  MBD_CLEAN_ALL: "no" ## Should be set to "yes" as soon as the testsuite is finished
  MBD_CLEAN_BUILD: "no" ## Clean up the build directory
  MBD_COMPILER_FLAGS: "-Ofast -Wall -march=native -mtune=native" ## Compiler flags for MBDyn and mboct-*-pkg
  MBOCT_OCTAVE_PKG_BRANCH: "master"
  MBOCT_NUMERICAL_PKG_BRANCH: "master"
  MBOCT_MBDYN_PKG_BRANCH: "master"
  MBOCT_FEM_PKG_BRANCH: "master"
  MBOCT_OCTAVE_PKG_REINSTALL: "no"
  MBOCT_NUMERICAL_PKG_REINSTALL: "no"
  MBOCT_MBDYN_PKG_REINSTALL: "no"
  MBOCT_FEM_PKG_REINSTALL: "no"
  MBD_GMSH_REINSTALL: "no"
  OCT_NETCDF_REINSTALL: "no"
  OCT_NURBS_REINSTALL: "no"

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

mbdyn-build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    #- echo "Check cpuinfo ..."
    #- cat /proc/cpuinfo
    #- echo "Check the host system ..."
    #- uname -a
    #- find ${HOME} -name config.status -execdir make distclean ';'
    - echo "Cleanup some garbage ..."
    - |
      for dirent in autom4te.cache build contrib CVS etc include libraries manual mbdyn modules packaging tests utils var; do
        if test -d ${HOME}/${dirent}; then
          #find ${HOME}/${dirent} -type f
          #rm -rf ${HOME}/${dirent}
        fi
      done
    #- echo "Check the contents of the home directory ..."
    #- find ${HOME} -type f # Let us check if we left some garbage there ...
    - printf "checkout branch \"%s\"\n" "$CI_COMMIT_BRANCH"
    - git checkout $CI_COMMIT_BRANCH --force
    - printf "pulling\n"
    - git pull --force
    ## Let's try to speed up the build process a bit
    ## Execute bootstrap.sh and configure only if needed
    ## This conditional execution may be removed as soon as the testsuite is finished
    - |
      if ! test -x ./configure ; then
        chmod u+x ./bootstrap.sh
        ./bootstrap.sh
      fi
      test -x ./configure
    - MBD_SOURCE_DIR=`pwd`
    - echo "Create build directory ..."
    - |
      if test ${MBD_CLEAN_BUILD} = "yes" || test ${MBD_CLEAN_ALL} = "yes"; then
        echo "cleanup build directory ..."
        rm -rf ${MBD_BUILD_DIR}
      fi
    - echo "create build directory ..."
    - if ! test -d ${MBD_BUILD_DIR}; then mkdir -p ${MBD_BUILD_DIR}; fi
    - test -d ${MBD_BUILD_DIR}
    - if ! test -d ${MBD_INSTALL_PREFIX}; then mkdir -p ${MBD_INSTALL_PREFIX}; fi
    - test -d ${MBD_INSTALL_PREFIX}
    - cd ${MBD_BUILD_DIR}
    - echo "Build directory"
    - pwd
    - ls -lhF .
    - printf "configure ...\n"
    - |
      if ! test -f Makefile; then
        if ! PYTHON_VERSION=3 ${MBD_SOURCE_DIR}/configure \
                    CPPFLAGS="-I/usr/include/suitesparse -I/usr/include/trilinos -I/usr/lib64/python3.11/site-packages/numpy/core/include -I/usr/include/python3.11/ -I/usr/include/octave-8.4.0" \
                    CXXFLAGS="${MBD_COMPILER_FLAGS}" \
                    CFLAGS="${MBD_COMPILER_FLAGS}" \
                    FFLAGS="${MBD_COMPILER_FLAGS}" \
                    FCFLAGS="${MBD_COMPILER_FLAGS}" \
                    --enable-python \
                    --enable-octave \
                    --enable-install_test_progs \
                    --prefix=${MBD_INSTALL_PREFIX} \
                    --with-umfpack \
                    --with-klu \
                    --with-suitesparseqr \
                    --with-static-modules \
                    --disable-Werror \
                    --with-trilinos ; then
                    ## FIXME: We should not use --disable-Werror, but need to fix a few warnings caused by Octave's headers instead
                    ## FIXME: Add --enable-netcdf
          echo "Failed to run configure"
          exit 1
        fi
      fi
      test -f Makefile
    - echo "Determine the number of build jobs ..."
    - |
      if test -f /proc/cpuinfo ; then
        MBD_NUM_BUILD_JOBS=`awk 'BEGIN{max=1;}/^processor\>/{if ($3 + 1 >= max) max = $3 + 1; } END{ print max }' /proc/cpuinfo`;
      fi
    - printf "Compiling the code using %s jobs ...\n" ${MBD_NUM_BUILD_JOBS}
    - make -j${MBD_NUM_BUILD_JOBS}
    - echo "Clean up local installation directory"
    - rm -rf ${MBD_INSTALL_PREFIX}
    - printf "Install the code in \"%s\"\n" "${MBD_INSTALL_PREFIX}"
    - make install
    - echo "MBDyn version:"
    - ${MBD_INSTALL_PREFIX}/bin/mbdyn --version
    - echo "Run built-in unit tests"
    - make test

mboct-octave-pkg-build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
      - echo "mboct-octave-pkg build"
      - |
        if test ${MBOCT_OCTAVE_PKG_REINSTALL} = "no" && test ${MBD_CLEAN_ALL} = "no"; then
          if octave --eval 'pl=pkg("list", "mboct-octave-pkg"); exit(isempty(pl))'; then
            echo "mboct-octave-pkg is already installed"
            exit 0
          fi
        fi
      - git clone -b ${MBOCT_OCTAVE_PKG_BRANCH} https://github.com/octave-user/mboct-octave-pkg.git
      - make CXXFLAGS="${MBD_COMPILER_FLAGS}" -C mboct-octave-pkg install_local

mboct-numerical-pkg-build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
      - echo "mboct-numerical-pkg build"
      - |
        if test ${MBOCT_NUMERICAL_PKG_REINSTALL} = "no" && test ${MBD_CLEAN_ALL} = "no"; then
          if octave --eval 'pl=pkg("list", "mboct-numerical-pkg"); exit(isempty(pl))'; then
            echo "mboct-numerical-pkg is already installed"
            exit 0
          fi
        fi    
      - git clone -b ${MBOCT_NUMERICAL_PKG_BRANCH} https://github.com/octave-user/mboct-numerical-pkg.git
      - make CXXFLAGS="${MBD_COMPILER_FLAGS}" -C mboct-numerical-pkg install_local

# nurbs-build-job:       # This job runs in the build stage, which runs first.
#   stage: build
#   script:
#       - echo "nurbs build"
#       - |
#         if test ${OCT_NURBS_REINSTALL} = "no" && test ${MBD_CLEAN_ALL} = "no"; then
#           if octave --eval 'pl=pkg("list", "nurbs"); exit(isempty(pl))'; then
#             echo "nurbs is already installed"
#             exit 0
#           fi
#         fi
#       - octave-cli --eval "pkg install -verbose -local -forge nurbs"

# netcdf-build-job:       # This job runs in the build stage, which runs first.
#   stage: build
#   script:
#       - echo "netcdf build"
#       - |
#         if test ${OCT_NETCDF_REINSTALL} = "no" && test ${MBD_CLEAN_ALL} = "no"; then
#           if octave --eval 'pl=pkg("list", "netcdf"); exit(isempty(pl))'; then
#             echo "netcdf is already installed"
#             exit 0
#           fi
#         fi    
#       - octave-cli --eval "pkg install -verbose -local -forge netcdf"

mboct-mbdyn-pkg-build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
      - |
        if test ${MBOCT_MBDYN_PKG_REINSTALL} = "no" && test ${MBD_CLEAN_ALL} = "no"; then
          if octave --eval 'pl=pkg("list", "mboct-mbdyn-pkg"); exit(isempty(pl))'; then
            echo "mboct-mbdyn-pkg is already installed"
            exit 0
          fi
        fi       
      - git clone -b ${MBOCT_MBDYN_PKG_BRANCH} https://github.com/octave-user/mboct-mbdyn-pkg.git
      - make CXXFLAGS="${MBD_COMPILER_FLAGS}" -C mboct-mbdyn-pkg install_local

gmsh-build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
      - echo "gmsh build"
      - |
        if ${MBD_INSTALL_PREFIX}/bin/gmsh --version >& /dev/null && test ${MBD_GMSH_REINSTALL} = "no" && test ${MBD_CLEAN_ALL} = "no"; then
          echo "Gmsh is already installed ..."
          exit 0
        fi
      - wget http://www.gmsh.info/bin/Linux/gmsh-stable-Linux64.tgz
      - tar -zxvf gmsh-stable-Linux64.tgz
      - install gmsh-*.*.*-Linux64/bin/gmsh ${MBD_INSTALL_PREFIX}/bin
      - ${MBD_INSTALL_PREFIX}/bin/gmsh --version

mboct-fem-pkg-build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
      - echo "mboct-fem-pkg build"
      - |
        if test ${MBOCT_FEM_PKG_REINSTALL} = "no" && test ${MBD_CLEAN_ALL} = "no"; then
          if octave --eval 'pl=pkg("list", "mboct-fem-pkg"); exit(isempty(pl))'; then
            echo "mboct-fem-pkg is already installed"
            exit 0
          fi
        fi       
      - git clone -b ${MBOCT_FEM_PKG_BRANCH} https://github.com/octave-user/mboct-fem-pkg.git
      - make CXXFLAGS="${MBD_COMPILER_FLAGS}" -C mboct-fem-pkg install_local

mboct-mbdyn-pkg-unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
      - echo "mboct-mbdyn-pkg test"
      - export PATH=${MBD_INSTALL_PREFIX}/bin:${PATH} 
      - export AWKPATH=${MBD_INSTALL_PREFIX}/share/awk:${AWKPATH}
      - which mbdyn
      - mbdyn --version
      - which mbdyn2easyanim.sh
      - which gmsh
      - gmsh --version
      - rm -f fntests.out
      - octave --eval 'psta=pkg("list","mboct-mbdyn-pkg"); __run_test_suite__({psta{1}.dir},{})' >& fntests.out
      - awk -F ' ' 'BEGIN{ failed=9999; } /^  FAIL\>/{ failed = $2; } END { if (failed != 0) exit 1; }' fntests.out

deploy-job:      # This job runs in the deploy stage.
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
